// Generated by https://quicktype.io



export interface WhoBiographies {
  "@odata.context":  string;
  value:             Value[];
  "@odata.nextLink": string;
}

export interface Value {
  Id:               string;
  LastModified:     Date;
  PublicationDate:  Date;
  DateCreated:      Date;
  IncludeInSitemap: boolean;
  SystemSourceKey:  null;
  UrlName:          string;
  ItemDefaultUrl:   string;
  Summary:          string;
  Biography:        string;
  Title:            string;
  ParentId:         string;
  Provider:         Provider;
}

export enum Provider {
  OpenAccessProvider = "OpenAccessProvider",
}
